---
on:   # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - 'main'

env:
  TEST_TAG: eext:test

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Lint yaml files
        run: yamllint .
